
package visual;

// IMPLEMENTATION PENDING TO next version 1.7

//import control.AdmSettings;
//import data.DatosTickets;

/** Wating Messenger Window, made to inform and show something to the user while
 * a Cinema Tickets file is being saved or opened
 * @author Clark - ClarkCodes
 * @since 1.6
 */
public class FrmDialogWaitingMessenger extends javax.swing.JDialog
{
    //private DatosTickets.WaitingType waitingType; IMPLEMENTATION PENDING TO next version 1.7
    /** Creates new form FrmDialogWaitingMessenger */
    public FrmDialogWaitingMessenger ( java.awt.Frame parent, boolean modal)//, DatosTickets.WaitingType waitingType )
    {
        super( parent, modal );
        initComponents();
        setLocationRelativeTo( null );
        //this.waitingType = waitingType;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jProgressBar1 = new javax.swing.JProgressBar();
        labelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jProgressBar1.setValue(100);
        jProgressBar1.setIndeterminate(true);

        labelMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMessage.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
//        IMPLEMENTATION PENDING TO next version 1.7
//        labelMessage.setText( switch( waitingType )
//        {
//            case Opening -> AdmSettings.getLanguageBundle().getString( "lk_data_state_opening" );
//            case Saving -> AdmSettings.getLanguageBundle().getString( "lk_data_state_saving" );
//        } );
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel labelMessage;
    // End of variables declaration//GEN-END:variables
}
